---
- name: var test
  hosts: localhost
  gather_facts: no

  vars:
    machine1:
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
    joe_machine:
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"

    
  tasks:
    - name: display creds
      debug:
        msg:
        - "machine1 username {{ machine1['username'] }}"
        - "machine1 password {{ machine1['password'] }}"
        - "joe_machine username {{ joe_machine['username'] }}"
        # - "valut1 username {{ vault1['password'] }}"


  
    # - name: add dummy_host
    #   add_host:
    #   name: "dummy"
    #   user: "{{ ansible_user }}"
    #   password: "{{ ansible_password }}"

